### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by lilmoefow** [SoraZodia/Cannibalism#2] opened 2015-09-19 22:08 UTC
I've been playing around on my server and i decided to add your mod in my last pack update.  We started getting weird crashes from "S0FPacketSpawnMob" and i wasn't sure what was causing it. So i went through one by one removing then re-adding the mods that i added on the last update.  I first thought it might have been TurkeyUtils, but no luck..  Then i tried removing Cannibalism, the crashes stooped and I'm actually able to join the server again.   I don't think the crash is cause solely by your mod, because after googling the crash i have found that several people are getting it and they are all running different mods than i am.

Here is a crash log
http://pastebin.com/kGWV1JeD

The Client crashes from this, the server does not.

**Comment by lilmoefow** [comment] 2015-09-19 22:32
never mind... i jumped the gun on reporting the issue cause i started getting the crash again..

**Comment by SoraZodia** [comment] 2015-09-20 00:16
Did you add the mod back in after the crash stopped? The only possible cause I could think of is the Wendigo, but its spawn should be disabled by default.

**Comment by lilmoefow** [comment] 2015-09-20 01:26
The crashes stopped after i removed the mod, and i have not added it back in(I would like to).  Another thing i noticed was that the configs saved to the server in several different spots. A folder in the config folder called "Cannibalism" and a file called "Cannibalism"  but filed also saved outside of the config folder and they were called "config/cannibalism/cannibalism" and just a random folder called "cannibalism" .

**Comment by SoraZodia** [comment] 2015-09-20 01:32
The cannibalism folder is where the json(s) are stored, and is very unlikely to cause the crash you're having. 
From the looks of it, Cannibalism is the one causing the crash so I try to fix this.

**Comment by lilmoefow** [comment] 2015-09-20 01:42
does it cause mobs to bleed when they die? if so it might be an issue with ZeldaSwordSkills mod's Bombplants... i think they they "Harvest/Explode" they techically "die" so maybe a weird intraction between the 2... im gonna test a few things ill see what i come up with.

**Comment by lilmoefow** [comment] 2015-09-20 02:10
I loaded up the world save from my server in single player with Cannibalism added back in and i can't get it to crash.

**Comment by lilmoefow** [comment] 2015-09-20 02:32
Ok looking though the server files i get this here 
http://imgur.com/XFFQj1w
Showing the "cannibalism" folder that is there. But i cant actually access it 
http://imgur.com/8t9DHUC

Looking at it though the server "dashboard" it looks like this though, and the folder is empty
http://imgur.com/soHxUoX

but there is this random file down here
http://imgur.com/CvM1IIx

is that how the .json configs are suposed to save to the server??

**Comment by SoraZodia** [comment] 2015-09-20 03:03
No, there was supported to be a cannibalism folder inside the config folder
which contain a json file named cannibalism. But that shouldn't cause a
crash as I coded a failsafe for the mod incase something unexpected
happened to the json.

The json don't do anything to entity spawns either. It only adds the entity
name to a list that the knife checks when it interacts with a mob.

**Comment by lilmoefow** [comment] 2015-09-21 16:37
Just an update.. I Started getting that same crash again even after removing your mod.  So i started a fresh map to see if maybe i had messes with Entity ids from adding and removing mods in my testing of things.  So I have removed Turkey Utilities(while keeping cannibalism active) and The crashes have stopped and i can log back into the server again. I think its something on their end with the ducks and turkeys not interacting properly with the chickens.. I found a thread where they were referencing DisplayChicken over writing chickens to be the cause of the crash. 

https://www.spigotmc.org/threads/my-client-is-crashing.20612/

thats the thread I'm referring to.

**Comment by SoraZodia** [comment] 2015-09-22 00:08
From the looks of it, Turkey Utilities is likely the cause and not Cannibalism... Not much I can do there, I'll be closing the issue for now.

The crash is probably not related to chickens though, but in how the entities was registered into Minecraft's spawn list.

**Closed by SoraZodia** 2015-09-22 00:08 UTC
Labels: crash

**Comment by lilmoefow** [comment] 2015-09-22 01:52
Yeah sorry for the inconvenience.. and i have already reported it with the Turkey Utilities Dev.
